#!/bin/bash

# Bento Plymouth theme post-install and post-removal script.
# This script selects and enables an installed theme.
# It is expected to be run with root privileges.

echo "Show the Plymouth themes installed:"
ls /usr/share/plymouth/themes/

read -p "Enter the name for your chosen theme or type 'q' to quit: " theme

if [[ "$theme" == "q" ]]; then
    echo "Exiting without changes."
    exit 0
fi

echo "Attempting to set Plymouth theme to: ${theme}"

# Building the full path to the `.plymouth` file and using 
# ${theme}.plymouth to substitute the variable
PLYMOUTH_FILE="/usr/share/plymouth/themes/${theme}/${theme}.plymouth"

# Setup and update the 'default.plymouth' alternative while adding a
# new them to the list of options generated by update-alternatives
# (The arguments are : link name, name, path, priority)
update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth "$PLYMOUTH_FILE" 120

# Adding the Bento text theme
TEXT_THEME_NAME = "bento-text"
PLYMOUTH_FILE_TEXT = "/usr/share/plymouth/themes/${TEXT_THEME_NAME}/${TEXT_THEME_NAME}.plymouth"

# The Bento text theme is an additional alternative, with a slighly inferior priority
update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth "$PLYMOUTH_FILE_TEXT" 115

# Define the chosen them as the default alternative - This explicitely
# activates the selected theme.
echo "Setting '$theme' as the default Plymouth theme..."
update-alternatives --set default.plymouth "$PLYMOUTH_FILE"

# Update the initramfs to finish applying the changes
echo "Updating initramfs..."
update-initramfs -u

echo "Plymouth theme changed successfully. The new theme will show 
during next reboot."

exit 0
